version: '3'
services:
  dynamic_caustics:
    restart: always
    build: .
    container_name: 'dynamic_caustics'
    working_dir: '/root/opt'
    tty: true
    volumes:
      - ../opt:/root/opt
    environment:
      DISPLAY: $DISPLAY:0
